version: "3"
services:
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "egauge:1:1"
  egauge-collector:
    build: .
    depends_on:
      - kafka
